### ISSUE TITLE
Use SMT as backend to calculate the root of the initial storage slots

### ISSUE THREAD

**Issue by vlopes11** [FuelLabs/fuel-tx#127]
(fuel_merkle::sparse::MerkleTree)[https://docs.rs/fuel-merkle/0.2.0/fuel_merkle/sparse/struct.MerkleTree.html] isn't production-ready, and should be used when available

_Originally posted by @adlerjohn in https://github.com/FuelLabs/fuel-tx/pull/126#discussion_r879985002_

**Comment by adlerjohn** [comment]
Wait, the contract ID should still use a binary Merkle tree. Only contract storage (including initial contract storage) and contract balances use SMT.
