### ISSUE TITLE
InstructionResult Inconsistencies

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-tx#88]
InstructionResult is used inconsistently between panic and script result types:

```
    Panic {
        id: ContractId,
        reason: Word,
        pc: Word,
        is: Word,
    },
...
    ScriptResult {
        result: InstructionResult,
        gas_used: Word,
    },
```

The reason for the panic receipt is always an encoded `InstructionResult`, so it would be more user-friendly if the panic receipt used the InstructionResult rather than the encoded form.

**Comment by adlerjohn** [comment]
Hmmmm. Could you clarify? The specs for the two receipts are here: https://github.com/FuelLabs/fuel-specs/blob/38d259f1a239908c01f1471d8efe8c9e5a58e80f/specs/vm/opcodes.md#reading-guide

The ABI specs are here: https://github.com/FuelLabs/fuel-specs/blob/38d259f1a239908c01f1471d8efe8c9e5a58e80f/specs/protocol/abi.md#panic-receipt and here: https://github.com/FuelLabs/fuel-specs/blob/38d259f1a239908c01f1471d8efe8c9e5a58e80f/specs/protocol/abi.md#scriptresult-receipt.

It appears the ABI specs are inconsistent with the VM specs!

**Comment by Voxelot** [comment]
I see, so the panic receipt is only meant to include the `PanicReason` and not also include the encoded instruction. That makes sense since the ScriptResult will already include the instruction result. In that case it seems like we should have this:

```
    Panic {
        id: ContractId,
        reason: PanicReason,
        pc: Word,
        is: Word,
    },
...
    ScriptResult {
        result: InstructionResult,
        gas_used: Word,
    },
```

The VM is incorrectly setting up the panic receipt here (which is encoding the actual instruction along with panic reason): https://github.com/FuelLabs/fuel-vm/blob/master/src/interpreter/flow.rs#L210

**Comment by Voxelot** [comment]
After reviewing the specs and discussing more, ScriptResult is meant to be a boolean result, not an encoded panic reason / instruction. We should update the `ScriptResult` result to be a boolean or word and set it based on the updated specs here: https://github.com/FuelLabs/fuel-specs/issues/289
